# Variables
@baseurl = http://localhost:3333 

# Health check
GET {{baseurl}}/health

###

# Get rooms
GET {{baseurl}}/rooms

###

#create room
POST {{baseurl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "test room",
    "description": "this is a description"
}